from turbotext.resolve import RawMatch

class CNode: ...

def build_ctrie(items: list[tuple[str, str]]) -> CNode: ...
def build_aho_corasick(root: CNode) -> None: ...
def search_exact(root: CNode, text: str) -> list[RawMatch]: ...
def search_aho_corasick(root: CNode, text: str) -> list[RawMatch]: ...
def search_ac_fast(root: CNode, text: str) -> list[tuple[int, int, str]]: ...
def resolve_ll_fast(raw: list[tuple[int, int, str]]) -> list[tuple[int, int, str]]: ...
